#!/bin/bash
set -e

clear
. /etc/os-release
case ${VARIANT_ID:-$ID} in
arch|endeavouros|garuda)
repo="pacman-key -r 8F654886F17D497FEFE3DB448B15A6B0E9A3FA35 && pacman-key --lsign-key 8F654886F17D497FEFE3DB448B15A6B0E9A3FA35 && grep g14 /etc/pacman.conf || echo -e '\n[g14]\nServer = https://arch.asus-linux.org' >> /etc/pacman.conf"
install="pacman -S --noconfirm --needed"
;;
fedora)
repo="dnf copr enable lukenukem/asus-linux"
install="dnf install -y"
;;
opensuse-tumbleweed)
repo="zypper ar -f https://download.opensuse.org/repositories/home:/luke_nukem:/asus/openSUSE_Tumbleweed/ asus-linux"
install="zypper -y in"
remove_conflict_asusctl="zypper -y rm tlp"
remove_conflict_supergfxctl="zypper -y rm suse-prime"
;;
silverblue)
repo="grep copr:copr.fedorainfracloud.org:lukenukem:asus-linux /etc/yum.repos.d/asus.repo || echo -e '[copr:copr.fedorainfracloud.org:lukenukem:asus-linux]\nname=Copr repo for asus-linux owned by lukenukem\nbaseurl=https://download.copr.fedorainfracloud.org/results/lukenukem/asus-linux/fedora-$releasever-$basearch/\ntype=rpm-md\nskip_if_unavailable=True\ngpgcheck=1\ngpgkey=https://download.copr.fedorainfracloud.org/results/lukenukem/asus-linux/pubkey.gpg\nrepo_gpgcheck=0\nenabled=1\nenabled_metadata=1' >> /etc/yum.repos.d/asus.repo"
install="rpm-ostree install"
;;
*)
echo Unsupported distribution. Exiting. && exit 1
;;
esac

[[ $(cat /sys/devices/virtual/dmi/id/board_name) =~ ^(GV601VI|GV601VV|GV601VU|E410MA)$ && $(uname -r) != *rog* ]] && echo NOTE: Your kernel is missing some features! Follow directions on asus-linux.org to install the ROG kernel.
echo asusctl is a general CLI utility. supergfxctl is a GPU CLI utility. ROG GUI is an interface including both utilities.
PS3='Select an option indicating the package(s) to install (1-4): '
select packages in "rog-gui" "asusctl supergfxctl" "asusctl" "supergfxctl"
do [[ $packages ]] && break || echo Invalid selection. Try again.
done

[[ $packages == rog-gui ]] && packages=$([[ $ID == arch ]] && echo rog-control-center || echo asusctl-rog-gui)

clear
$repo
$install $packages
[[ $packages =~ (rog-gui|asusctl) ]] && $remove_conflict_asusctl && systemctl enable --now power-profiles-daemon && systemctl start asusd
[[ $packages =~ (rog-gui|supergfxctl) ]] && $remove_conflict_supergfxctl && systemctl enable --now supergfxd
